-- =============================================================================
-- EduPulse AI — Seed Data
-- Initial data for departments, rooms, semester, courses, admin user, settings
-- =============================================================================

-- Departments
INSERT INTO departments (department_name, department_code, building) VALUES
    ('Computer Science', 'CS', 'Science Building'),
    ('Mathematics', 'MATH', 'Science Building')
ON CONFLICT (department_code) DO NOTHING;

-- Rooms (from current CSV data: Room 204, Room 305, Room 401, Room 501)
INSERT INTO rooms (room_number, building, capacity, room_type, equipment) VALUES
    ('Room 204', 'Science Building', 30, 'Lecture Hall', ARRAY['projector', 'camera', 'whiteboard']),
    ('Room 305', 'Science Building', 30, 'Lecture Hall', ARRAY['projector', 'camera', 'whiteboard']),
    ('Room 401', 'Science Building', 30, 'Lecture Hall', ARRAY['projector', 'camera', 'whiteboard']),
    ('Room 501', 'Science Building', 30, 'Lecture Hall', ARRAY['projector', 'camera', 'whiteboard'])
ON CONFLICT (room_number, building) DO NOTHING;

-- Semesters
INSERT INTO semesters (semester_id, semester_name, start_date, end_date, is_active) VALUES
    ('SPRING2026', 'Spring 2026', '2026-02-09', '2026-05-31', TRUE)
ON CONFLICT (semester_id) DO NOTHING;

-- Courses
INSERT INTO courses (course_code, course_name, department_id, credit_hours, description) VALUES
    ('CS301', 'Artificial Intelligence',
        (SELECT department_id FROM departments WHERE department_code = 'CS'), 3,
        'Fundamentals of AI including search, reasoning, and machine learning'),
    ('CS302', 'Data Science Fundamentals',
        (SELECT department_id FROM departments WHERE department_code = 'CS'), 3,
        'Introduction to data science, statistical analysis, and data visualization'),
    ('CS401', 'Advanced Machine Learning',
        (SELECT department_id FROM departments WHERE department_code = 'CS'), 4,
        'Advanced topics in ML including deep learning, NLP, and reinforcement learning'),
    ('MATH201', 'Statistics for Data Analysis',
        (SELECT department_id FROM departments WHERE department_code = 'MATH'), 3,
        'Statistical methods for data analysis and interpretation')
ON CONFLICT (course_code) DO NOTHING;

-- Admin user (password: admin123 — bcrypt hash generated by pgcrypto)
INSERT INTO users (username, email, password_hash, role, is_active) VALUES
    ('admin', 'admin@edupulse.edu',
     crypt('admin123', gen_salt('bf')), 'admin', TRUE)
ON CONFLICT (username) DO NOTHING;

-- Admin profile
INSERT INTO admins (user_id, full_name)
SELECT user_id, 'Administrator'
FROM users WHERE username = 'admin'
ON CONFLICT (user_id) DO NOTHING;

-- Semester Weeks (16 weeks: Feb 9 - May 24, 2026)
INSERT INTO semester_weeks (semester_id, academic_week, week_label, start_date, end_date, status) VALUES
    ('SPRING2026', 1,  'Week 1',  '2026-02-09', '2026-02-15', 'completed'),
    ('SPRING2026', 2,  'Week 2',  '2026-02-16', '2026-02-22', 'completed'),
    ('SPRING2026', 3,  'Week 3',  '2026-02-23', '2026-03-01', 'completed'),
    ('SPRING2026', 4,  'Week 4',  '2026-03-02', '2026-03-08', 'completed'),
    ('SPRING2026', 5,  'Week 5',  '2026-03-09', '2026-03-15', 'completed'),
    ('SPRING2026', 6,  'Week 6',  '2026-03-16', '2026-03-22', 'scheduled'),
    ('SPRING2026', 7,  'Week 7',  '2026-03-23', '2026-03-29', 'scheduled'),
    ('SPRING2026', 8,  'Week 8',  '2026-03-30', '2026-04-05', 'scheduled'),
    ('SPRING2026', 9,  'Week 9',  '2026-04-06', '2026-04-12', 'scheduled'),
    ('SPRING2026', 10, 'Week 10', '2026-04-13', '2026-04-19', 'scheduled'),
    ('SPRING2026', 11, 'Week 11', '2026-04-20', '2026-04-26', 'scheduled'),
    ('SPRING2026', 12, 'Week 12', '2026-04-27', '2026-05-03', 'scheduled'),
    ('SPRING2026', 13, 'Week 13', '2026-05-04', '2026-05-10', 'scheduled'),
    ('SPRING2026', 14, 'Week 14', '2026-05-11', '2026-05-17', 'scheduled'),
    ('SPRING2026', 15, 'Week 15', '2026-05-18', '2026-05-24', 'scheduled'),
    ('SPRING2026', 16, 'Week 16', '2026-05-25', '2026-05-31', 'scheduled')
ON CONFLICT (semester_id, academic_week) DO NOTHING;

-- System Settings
INSERT INTO system_settings (setting_key, setting_value, setting_type, description) VALUES
    ('confusion_threshold', '0.30', 'float', 'Threshold for confusion spike alerts (percentage of confused students)'),
    ('boredom_threshold', '0.30', 'float', 'Threshold for boredom spike alerts'),
    ('capture_interval_seconds', '5', 'integer', 'Seconds between camera frame captures'),
    ('model_name', 'EduPulse_v1.0', 'string', 'Default emotion detection model name'),
    ('session_timeout_hours', '24', 'integer', 'Login session expiration in hours'),
    ('max_login_attempts', '5', 'integer', 'Max failed login attempts before lockout'),
    ('app_version', '0.3.0', 'string', 'Current application version'),
    ('institution_name', 'University', 'string', 'Institution display name')
ON CONFLICT (setting_key) DO NOTHING;
